# Generated by Django 4.2.5 on 2023-10-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_customer_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default=models.CharField(max_length=60), max_length=120
            ),
        ),
    ]
