# Generated by Django 4.2.5 on 2023-11-30 23:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_order_options_order_created_order_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=30, unique=True)),
                (
                    "valid_from",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 8, 0, 28, 45, 232685)
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
