# Generated by Django 4.2.5 on 2024-01-31 21:08

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_discountcoupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                error_messages={"invalid": "Please enter a valid phone number"},
                max_length=16,
                region="PL",
            ),
        ),
        migrations.AlterField(
            model_name="discountcoupon",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 7, 21, 8, 45, 507562)
            ),
        ),
    ]
