# Generated by Django 4.2.5 on 2023-11-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="counter",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity"),
        ),
    ]
